### ISSUE TITLE
Derive from prog-mode or conf-mode

### ISSUE THREAD

**Issue by swsnr** [brocode/play-routes-mode#2]
Hello,

thank you very much for this mode.  It's already helping me a lot, but I'd like to make a suggestion for an even better mode: Did you consider deriving from conf-mode?  I think it'd provide a bit of basic functionality out of the box, and it'd simplify Emacs configuration, because by running `conf-mode-hook` a lot of user's configuration for configuration modes comes in automatically.

**Comment by bomgar** [comment]
IMHO the file is some strange hybrid between prog-mode and conf-mode. I decided to use prog-mode. 
I'm interessted in your conf mode hooks. What kind of hooks do you have?

**Comment by swsnr** [comment]
@bomgar Well, the usual stuff: `smartparens-mode`, `flyspell-prog-mode`, etc.

**Comment by swsnr** [comment]
Thank you for updating the mode so quickly!
