### ISSUE TITLE
Define comment syntax

### ISSUE THREAD

**Issue by swsnr** [brocode/play-routes-mode#3]
To support `comment-dwim` and similar commands the mode should define a comment syntax.

Note that I think #2 would also solve this, because as far as I know `conf-mode` automatically sets the comment syntax to `#`.

**Comment by bomgar** [comment]
Is this sufficient for your use case?

**Comment by swsnr** [comment]
@bomgar Absolutely!  Thank you very much for this change, and for this great mode!
